name: MacOS

on:
  push:
    branches:
          - main
          - master
          - 'releases/**'
  pull_request:
jobs:
  launch:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Raku/setup-raku@v1
      with:
        raku-version: latest
    - run: bin/setup.sh

