name: NixOS

on:
  push:
    branches:
          - main
          - master
          - 'releases/**'
  pull_request:
jobs:
  launch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: bin/setup.sh
